jobs:
- job: Windows
  pool:
    vmImage: 'win1803'
  timeoutInMinutes: 120
  steps:
  - script: |
      choco install docker-compose
      choco install --no-progress --yes --version=3.7.2 python3
      export "PATH=C:\Python37;C:\Python37\Scripts;%PATH%
      python build.py
    env:
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
  strategy:
    matrix:
      Visual Studio 2015 14.0:
        VISUAL_VERSIONS: "14"
      Visual Studio 2017 15.0:
        VISUAL_VERSIONS: "15"
