jobs:
- job: Windows
  pool:
    vmImage: 'win1803'
  timeoutInMinutes: 120
  steps:
  - script: |
      choco install docker-compose
      choco install python3
      refreshenv
      python build.py
    env:
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
  strategy:
    matrix:
      Visual Studio 2015 14.0:
        VISUAL_VERSIONS: "14"
      Visual Studio 2017 15.0:
        VISUAL_VERSIONS: "15"
