FROM conanio/msvcbase

LABEL maintainer="Luis Martinez de Bartolome <luism@jfrog.com>"

RUN choco install --no-progress --yes microsoft-build-tools --version 12.0.21005.20140416 -ia "/Full"
RUN RefreshEnv
